<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401100301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE professionals ALTER verified DROP DEFAULT');
        $this->addSql('ALTER TABLE professionals ALTER degrees DROP DEFAULT');
        $this->addSql('ALTER TABLE professionals ALTER areas_of_expertise DROP DEFAULT');
        $this->addSql('ALTER TABLE professionals ALTER specialities DROP DEFAULT');
        $this->addSql('ALTER TABLE reviews ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reviews ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reviews.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_6970eb0fdc0bd19f RENAME TO IDX_6970EB0FDB77003');
        $this->addSql('ALTER TABLE services ALTER cost TYPE DOUBLE PRECISION');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE professionals ALTER verified SET DEFAULT false');
        $this->addSql('ALTER TABLE professionals ALTER degrees SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE professionals ALTER areas_of_expertise SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE professionals ALTER specialities SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE reviews ALTER id SET DEFAULT nextval(\'reviews_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reviews ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reviews.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_6970eb0fdb77003 RENAME TO idx_6970eb0fdc0bd19f');
        $this->addSql('ALTER TABLE services ALTER cost TYPE NUMERIC(10, 2)');
    }
}
