<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328182642 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX admin_email_unique ON admins (email)');
        $this->addSql('CREATE TABLE appointments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_name VARCHAR(200) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, professional_id INT NOT NULL, user_id INT NOT NULL, service_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A41727ADB77003 ON appointments (professional_id)');
        $this->addSql('CREATE INDEX IDX_6A41727AA76ED395 ON appointments (user_id)');
        $this->addSql('CREATE INDEX IDX_6A41727AED5CA9E6 ON appointments (service_id)');
        $this->addSql('CREATE INDEX IDX_6A41727ADB77003A76ED395 ON appointments (professional_id, user_id)');
        $this->addSql('CREATE INDEX IDX_6A41727AAA9E377A ON appointments (date)');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_role VARCHAR(20) NOT NULL, recipient_role VARCHAR(20) NOT NULL, content TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_user_id INT DEFAULT NULL, sender_professional_id INT DEFAULT NULL, recipient_user_id INT DEFAULT NULL, recipient_professional_id INT DEFAULT NULL, appointment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E962A98155E ON messages (sender_user_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96F0B0FF4 ON messages (sender_professional_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96B15EFB97 ON messages (recipient_user_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96581A650A ON messages (recipient_professional_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96E5B533F9 ON messages (appointment_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96B15EFB978B8E8428 ON messages (recipient_user_id, created_at)');
        $this->addSql('CREATE INDEX IDX_DB021E96581A650A8B8E8428 ON messages (recipient_professional_id, created_at)');
        $this->addSql('CREATE TABLE professionals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, business_name VARCHAR(200) DEFAULT NULL, job VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, languages JSON NOT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX professional_email_unique ON professionals (email)');
        $this->addSql('CREATE UNIQUE INDEX professional_username_unique ON professionals (username)');
        $this->addSql('CREATE TABLE services (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, cost NUMERIC(10, 2) NOT NULL, duration INT DEFAULT NULL, languages JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, professional_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7332E169DB77003 ON services (professional_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, languages JSON NOT NULL, avatar VARCHAR(255) DEFAULT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX user_email_unique ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX user_username_unique ON users (username)');
        $this->addSql('ALTER TABLE appointments ADD CONSTRAINT FK_6A41727ADB77003 FOREIGN KEY (professional_id) REFERENCES professionals (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointments ADD CONSTRAINT FK_6A41727AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointments ADD CONSTRAINT FK_6A41727AED5CA9E6 FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E962A98155E FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F0B0FF4 FOREIGN KEY (sender_professional_id) REFERENCES professionals (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96B15EFB97 FOREIGN KEY (recipient_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96581A650A FOREIGN KEY (recipient_professional_id) REFERENCES professionals (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96E5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E169DB77003 FOREIGN KEY (professional_id) REFERENCES professionals (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointments DROP CONSTRAINT FK_6A41727ADB77003');
        $this->addSql('ALTER TABLE appointments DROP CONSTRAINT FK_6A41727AA76ED395');
        $this->addSql('ALTER TABLE appointments DROP CONSTRAINT FK_6A41727AED5CA9E6');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E962A98155E');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F0B0FF4');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96B15EFB97');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96581A650A');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96E5B533F9');
        $this->addSql('ALTER TABLE services DROP CONSTRAINT FK_7332E169DB77003');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE appointments');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE professionals');
        $this->addSql('DROP TABLE services');
        $this->addSql('DROP TABLE users');
    }
}
