controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

graphql:
    path: /graphql
    controller: App\Controller\GraphQLController::handle
    methods: [GET, POST]
